function compile_c(obj)
% complile the C codes

class_folder =  fileparts(mfilename('fullpath'));
%mex([class_folder, filesep,'c_code/pempc_solve_couple_mex.c']...
%    ,[class_folder, filesep,'c_code/pempc.c']...
%    , '-R2017b','-lmwblas','-silent');
%mex('-O','-LargeArrayDims','CFLAGS="$CFLAGS -fopenmp"','LDFLAGS="$LDFLAGS -fopenmp"','-R2017b','-lmwblas','-silent'...
%    ,[class_folder, filesep,'c_code/pempc_solve_decouple_mex.c']...
%    ,[class_folder, filesep,'c_code/pempc.c']...
%    );
if exist('pempc_get_control_mex.mexw64', 'file')
    delete('pempc_get_control_mex.mexw64');
end

myCCompiler = mex.getCompilerConfigurations('C','Selected');

if contains(myCCompiler.Name, 'Microsoft')
    %%% If the system is using Microsoft Visual C compiler
    %%% Note: Microsoft C compiler does not support Variable Length
    %%% Array...
    compiler_flags = 'COMPFLAGS="$COMPFLAGS /std:c11"';
    error("The compiler %s is not supported, please consider install MinGW compiler.\n" + ...
        "Please run `mex -setup` to change your compiler.\n" + ...
        "You may also want to install the MATLAB Support for MinGW-w64 C/C++/Fortran Compiler from the folloing link\n" + ...
        "https://ww2.mathworks.cn/matlabcentral/fileexchange/52848-matlab-support-for-mingw-w64-c-c-fortran-compiler", ...
        myCCompiler.Name);
else
    compiler_flags = 'CFLAGS="$CFLAGS -fopenmp -std=c11"';
end

mex('-g','-LargeArrayDims', compiler_flags,'LDFLAGS="$LDFLAGS -fopenmp"','-R2017b','-lmwblas','-silent',...
        [class_folder, filesep,'c_code/peMPC_controller_mex.c'],...
        [class_folder, filesep,'c_code/pempc.c']...
        );
fprintf("MEX-files successfully compiled.\n");
end